//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeviceVideosDBEntities1 : DbContext
    {
        public DeviceVideosDBEntities1()
            : base("name=DeviceVideosDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DeviceBrand> DeviceBrands { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<DeviceType> DeviceTypes { get; set; }
        public virtual DbSet<UploaderTime> UploaderTimes { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<View> Views { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Senior> Seniors { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Buyer> Buyers { get; set; }
        public virtual DbSet<Income> Incomes { get; set; }
        public virtual DbSet<Uploader> Uploaders { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
    }
}
