//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public long Id { get; set; }
        public long VideoId { get; set; }
        public long BuyerId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual Video Video { get; set; }
    }
}
