//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Videos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Videos()
        {
            this.Feedbacks = new HashSet<Feedbacks>();
        }
    
        public long VideoId { get; set; }
        public long UploaderId { get; set; }
        public long DeviceId { get; set; }
        public long LanguageId { get; set; }
        public long Views { get; set; }
        public bool Blocked { get; set; }
        public string Url { get; set; }
        public decimal Price { get; set; }
        public bool Approved { get; set; }
    
        public virtual Devices Devices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedbacks> Feedbacks { get; set; }
        public virtual Languages Languages { get; set; }
        public virtual Uploaders Uploaders { get; set; }
    }
}
