//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Video()
        {
            this.Feedbacks = new HashSet<Feedback>();
            this.Incomes = new HashSet<Income>();
            this.Views1 = new HashSet<View>();
        }
    
        public long VideoId { get; set; }
        public long UploaderId { get; set; }
        public long DeviceId { get; set; }
        public long LanguageId { get; set; }
        public long Views { get; set; }
        public bool Blocked { get; set; }
        public string Url { get; set; }
        public string SubUrl { get; set; }
        public decimal Price { get; set; }
        public bool Approved { get; set; }
        public System.DateTime Date { get; set; }
        public double AverageRating { get; set; }
        public double Duration { get; set; }
        public bool Disabled { get; set; }
    
        public virtual Device Device { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Income> Incomes { get; set; }
        public virtual Language Language { get; set; }
        public virtual Uploader Uploader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<View> Views1 { get; set; }
    }
}
